### ISSUE TITLE
Documentation improvements for: /streams-api/evm/webhook-security

### ISSUE THREAD

**Issue by lemonyatko** [MoralisWeb3/docs#140]
**Is your feature request related to a problem? Please describe.**
outdated docs or not matching with another [doc](https://docs.moralis.io/streams-api/evm/webhooks-transactions#verify-webhooks)

**Describe the solution you'd like**
replace js code example with native method of your package
```js
import Moralis from "moralis";

const { headers, body } = request;

Moralis.Streams.verifySignature({
  body,
  signature: headers["x-signature"],
}); // throws error if not valid
```

**Describe alternatives you've considered**
or just add this code as alternative

**Additional context**
-

**Comment by YosephKS** [comment]
Hey @lemonyatko,

Thanks for creating an issue here 😄 

Can you clarify what is outdated on the docs? The code should have been up-to-date and looks like it's all using the SDK methods.

If you can point to the details of individual pages, let me know about it and I can work on it

**Comment by lemonyatko** [comment]
also (here)[https://docs.moralis.io/streams-api/evm/response-body#how-to-verify-the-signature-for-the-received-webhook-request]

**Comment by YosephKS** [comment]
Hey @lemonyatko,

Thanks for the details! Understood.

Let me get back to the devs and see whether this is equivalent to our `verifySignature` API. If so, we can make the changes to instead use Moralis API for this.

I'll get back to you once I have a reply.

**Comment by YosephKS** [comment]
Hey @lemonyatko 

I just got word from our devs and looks like while the function has the same name as our API, they are not equivalent and therefore not replaceable to our `verifySignature` API.

For now, I'm going to close this issue, but feel free to create a new one if you found any other issue arises~

Have a nice day!
