### ISSUE TITLE
Feature request for: /web3-data-api/evm/market-data-api/

### ISSUE THREAD

**Issue by amanotullah** [MoralisWeb3/docs#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amanotullah** [comment]
Data

**Comment by YosephKS** [comment]
Hey @amanotullah,

Thanks for opening an issue here. Can you clarify what this issue is about?

**Comment by YosephKS** [comment]
Hey @amanotullah,

Since the scope of this issue is not so clear, I'll be closing this issue at the moment.

However, if you have any other suggestion, feel free to create a new issue~
