### ISSUE TITLE
Feature request for: /web3-data-api/evm/get-your-api-key

### ISSUE THREAD

**Issue by Tahiroun75** [MoralisWeb3/docs#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YosephKS** [comment]
Hey @Tahiroun75,

Thanks for opening a new issue at Moralis documentation repository~

Can you give more detail on any issue with the page you are referring to in the title?
