### ISSUE TITLE
Feature request for: /web3-data-api/evm/market-data-api/

### ISSUE THREAD

**Issue by RajARROW** [MoralisWeb3/docs#200]
The market api does not include network in the response for each token. It is required as many times user need to know the network of the coin to use the token ID an interaction with the network.

It would be great if we can have an addition field by network or chainId name which can let user know the network of the coin.

**Comment by JohnVersus** [comment]
Hi @RajARROW  

We have noted this. This will be updated in future updates of this API. 

You can track it on our roadmap
https://roadmap.moralis.io/b/feature-requests/market-data-api-top-nft-collections-address
