### ISSUE TITLE
Feature request for: /web3-data-api/evm/reference/wallet-api/get-chain-activity-by-wallet

### ISSUE THREAD

**Issue by RZ7272** [MoralisWeb3/docs#260]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JohnVersus** [comment]
Hi @RZ7272  

Can you please post your question on the Moralis forum? This repository is only for documentation. 
https://forum.moralis.io/
