### ISSUE TITLE
Feature request for: /web3-data-api/evm/reference/get-top-nft-collections-by-market-cap

### ISSUE THREAD

**Issue by mystery000** [MoralisWeb3/docs#261]
I appreciate if if you could upgrade this api to get the top NFTs in each platform.

* Top NFTs in Ethereum network
* Top NFTs in Polygon network.
* Arbitrum and BNB chain.

Also I would like to get the NFT collection address as response.
Currently, there is no contract address in the response.

**Comment by JohnVersus** [comment]
Hi @mystery000 

I recommend posting this information on our [roadmap](https://roadmap.moralis.io/) site. You can find a similar request on the below page. If you want to add more information or upvote the existing post, please use the below page.
https://roadmap.moralis.io/b/feature-requests/market-data-api-top-nft-collections-address
