### ISSUE TITLE
Issues with https://moralis.io/how-to-write-a-solana-smart-contract post

### ISSUE THREAD

**Issue by ksolana** [MoralisWeb3/docs#362]
**Describe the bug**
Issues with https://moralis.io/how-to-write-a-solana-smart-contract

1. it doesn't specify the yarn commands needed to run the app. I had to go to the project github page to figure out the commands.
2. yarn install doesn't work as the code needs upgrade to newer node versions
3. The instructions to get the API key also doesn't match the current view when I log in.

**To Reproduce**
1. Follow the doc and you'll get stuck

**Expected behavior**
All commands expected to work as documented.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 6.5.12-100.fc37.x86_64

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JohnVersus** [comment]
the project was tested with the npm package manager it should work with the same. To work with yarn you will have to modify your node version as the error or warning suggests
