### ISSUE TITLE
Feature request for: /web3-data-api/solana/reference/get-sol-token-price

### ISSUE THREAD

**Issue by Stephegbenga** [MoralisWeb3/docs#413]
**Is your feature request related to a problem? Please describe.**
No, It's not a problem, 

**Describe the solution you'd like**
I'll be glad if there is an option to get the price of a solana token at a certain time in the past 
**Describe alternatives you've considered**

**Additional context**

**Comment by salisbury88** [comment]
Hey @Stephegbenga , we are currently working on historical prices for Solana 🤩 We expect to be live with it early Q3.
