### ISSUE TITLE
Feature request for: /web3-data-api/evm/reference/get-wallet-transactions

### ISSUE THREAD

**Issue by TaylorDurden** [MoralisWeb3/docs#420]
**Is your feature request related to a problem? Please describe.**
https://docs.moralis.io/web3-data-api/evm/reference/get-wallet-transactions?address=0x1f9090aaE28b8a3dCeaDf281B0F12828e676c326&chain=eth&order=DESC
This api response result is a object, shouldn't be an array of objects?
![image](https://github.com/MoralisWeb3/docs/assets/7043731/717a414d-4d57-4717-b0cd-48c379bb9d99)

**Comment by WoodsFiend** [comment]
I have seen this on several endpoints examples when building out an SDK. Pretty much any time there is a "result" it should be an array.

**Comment by JohnVersus** [comment]
Thanks for the report. This will be fixed soon.
