### ISSUE TITLE
Feature request for: /web3-data-api/evm/reference/wallet-api/get-wallet-net-worth

### ISSUE THREAD

**Issue by WoodsFiend** [MoralisWeb3/docs#425]
**Is your feature request related to a problem? Please describe.**
The address example value for testing Wallet Net Worth now has too many ERC20 token balances and doesn't return a result.
https://docs.moralis.io/web3-data-api/evm/reference/wallet-api/get-wallet-net-worth?address=0xd8da6bf26964af9d7eed9e03e53415d37aa96045&chains=[]&exclude_spam=true&exclude_unverified_contracts=true

**Describe the solution you'd like**
Select an address that returns a correct response.

**Describe alternatives you've considered**
Include multiple options so that all potential responses can be tested. The default should be a successful response with options for others.

**Additional context**
![image](https://github.com/MoralisWeb3/docs/assets/35517586/9b2afdf8-a308-41df-b364-e9118682d020)

**Comment by JohnVersus** [comment]
Hi @WoodsFiend Thanks for the report. The example address will be updated soon.
