### ISSUE TITLE
Feature request for: /web3-data-api/evm/how-to-get-historical-erc20-token-price

### ISSUE THREAD

**Issue by cbueltem** [MoralisWeb3/docs#445]
The article describes how to get historical token prices. This is done by specifying the block number to which the price should be queried.
It would be helpful to describe on how the block relstes to a certain point in time. I.e. if I want to fetch historical prices, I will e.g. want daily datapoints. So what is the block I need to use that translates to a certain point of time.

**Comment by JohnVersus** [comment]
Hi @cbueltem 

You can use getDateToBlock endpoint to get the block number at a point in time. Have a look at the below docs for testing. 
https://docs.moralis.io/web3-data-api/evm/reference/get-date-to-block
