### ISSUE TITLE
bug in supported chain list 

### ISSUE THREAD

**Issue by harissatti** [MoralisWeb3/docs#450]
its an issue in the code .

In supported chain their is an issue that fantom testnet **type** is write as mainnet  not a **testnet** .
it must be change to the **testnet** because it's a testnet  not mainnet  .change it before someone may be misguided. 
Thanks

**link is:**
[https://docs.moralis.io/supported-chains?list=evm](url)
![moralis](https://github.com/MoralisWeb3/docs/assets/58341295/fe1075a2-de38-47e6-b2b6-496a04824a11)

**Comment by JohnVersus** [comment]
<img width="637" alt="image" src="https://github.com/MoralisWeb3/docs/assets/15834299/ce4b1ad2-0081-4209-a819-44d47b6d7576">
